name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22' # Use the Node.js version required by your Angular project

    - name: Install dependencies
      run: npm install

    - name: Build Angular project
      run: npm run build --prod

    - name: Copy files to web server directory
      run: |
        sudo rm -rf /var/www/html/gnosi/*               # Remove existing files from web server directory
        sudo cp -R dist/your-angular-app/* /var/www/html/gnosi/  # Copy new build files to web server directory
